name: Social
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  bluesky:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node ⬇️
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: 18
      - name: Checkout code 👋
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Skyt 🌤️
        working-directory: scripts/bluesky
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          OWNER: JanDeDobbeleer
          REPO: oh-my-posh
        run: |
          npm install
          node main.cjs
